config/routes.rb
Rails.application.routes.draw do

  resources :hotels , shallow:true do
    resources :rooms
  end
  root "hotels#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
  validates :name, uniqueness: {case_sensitive: false} ,presence: true
  validates :address,uniqueness: {case_sensitive: false}, presence: true
  validates :description, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: %i[ show edit update destroy ]

  def index
    @hotels = Hotel.all
  end

  def show
  end

  def new
    @hotel = Hotel.new
  end

  def edit
  end

  def create
    hotel_create = Hotels::HotelCreationService.new(hotel_params)

    respond_to do |format|
      if hotel_create.create_hotel
        format.html { redirect_to new_hotel_room_path(hotel_create.hotel.id), notice: "Hotel was successfully created." }
        format.json { render :show, status: :created, location: hotel_create.hotel.id }
      else
        @hotel = hotel_create.hotel
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    hotel_update = Hotels::HotelUpdateService.new(@hotel, hotel_params)
    respond_to do |format|
      if hotel_update.update_hotel
        format.html { redirect_to hotel_url(@hotel), notice: "Hotel was successfully updated." }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    hotel_destroy = Hotels::HotelDestroyService.new(@hotel)
    hotel_destroy.destroy_hotel
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: "Hotel was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit(:name, :address, :description)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  before_action :set_hotel, only: [:new, :create]
  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = @hotel.rooms.build(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to room_url(@room), notice: "Room was successfully created." }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "Room was successfully updated." }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy!

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def set_hotel
    @hotel = Hotel.find(params[:hotel_id])
  end

  def room_params
    params.require(:room).permit(:room_code, :description, :price_per_nigth, :hotel_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/hotels/_form.html.erb
<%= form_with(model: obj, local: true) do |form| %>
  <div class="col-sm-2">
    <div>
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>
  </div>

  <div class="col-sm-2">
    <div>
      <%= form.label :address, class: 'form-label' %>
      <%= form.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div class="col-sm-2">
    <div>
      <%= form.label :description, class: 'form-label' %>
      <%= form.text_area :description, class: 'form-control' %>
    </div>
  </div>


  <div class="mt-2">
    <%= form.submit "Create Hotel",class: 'btn btn-primary'%>
  </div>

<% end %>

app/views/hotels/_hotel.html.erb
<h5 class="card-title"><strong>Name:</strong> <%= hotel.name %></h5>
<p class="card-text"><strong>Address:</strong> <%= hotel.address %></p>
<p class="card-text"><strong>Description:</strong> <%= hotel.description %></p>

app/views/hotels/edit.html.erb
<h1>Editing hotel</h1>
<%= render "shared/error", obj: @hotel %>
<%= render "form", obj: @hotel %>

<br>

<div>
  <%= link_to "Show this hotels", @hotel %> |
  <%= link_to "Back to hotels", hotels_path %>
</div>

app/views/hotels/index.html.erb
<h1>Hotels</h1>


<% @hotels.each do |hotel| %>
  <div id="<%= dom_id hotel %>" class="card mt-3">
    <div class="card-body ">
      <%= render hotel %>
      <br/>
      <%= link_to "Show this hotels", hotel, class: "btn btn-secondary btn-sm" %>
    </div>
  </div>

<% end %>

<%= link_to "New hotels", new_hotel_path, class: "btn btn-success mt-2" %>

app/views/hotels/new.html.erb
<h1>New hotel</h1>
<%= render 'shared/error', obj: @hotel %>
<%= render "form", obj: @hotel %>
<br>

<div>
  <%= link_to "Back to hotels", hotels_path ,class: "btn btn-secondary mt-2" %>
</div>

app/views/hotels/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @hotel %>

<div>
  <%= link_to "Edit this hotels", edit_hotel_path(@hotel) %> |
  <%= link_to "Back to hotels", hotels_path %>

  <%= button_to "Destroy this hotels", @hotel, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectFinal1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: [@hotel, room]) do |form| %>

  <div>
    <%= form.label :room_code, style: "display: block" %>
    <%= form.text_field :room_code %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price_per_nigth, style: "display: block" %>
    <%= form.text_field :price_per_nigth %>
  </div>

  <div>
    <%= form.label :hotel_id, style: "display: block" %>
    <%= form.text_field :hotel_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<div id="<%= dom_id room %>">
  <p>
    <strong>Room code:</strong>
    <%= room.room_code %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= room.description %>
  </p>

  <p>
    <strong>Price per nigth:</strong>
    <%= room.price_per_nigth %>
  </p>

  <p>
    <strong>Hotel:</strong>
    <%= room.hotel_id %>
  </p>

</div>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Show this room", @room %> |
  <%= link_to "Back to rooms", rooms_path %>
</div>

app/views/rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Rooms</h1>

<div id="rooms">
  <% @rooms.each do |room| %>
    <%= render room %>
    <p>
      <%= link_to "Show this room", room %>
    </p>
  <% end %>
</div>

<%= link_to "New room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render "form", room: @room %>

<br>

<div>
  <%= link_to "Hotel", @hotel , class: "btn btn-primary"%>
</div>

app/views/rooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room %>

<div>
  <%= link_to "Edit this room", edit_room_path(@room) %> |
  <%= link_to "Back to rooms", rooms_path %>

  <%= button_to "Destroy this room", @room, method: :delete %>
</div>

app/views/shared/_error.html.erb
<% if obj && obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading"><%= pluralize(obj.errors.count, 'error') %> prohibited this room from being saved:</h4>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>